- name: Update and upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
    state: latest

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - git
      - python3-setuptools
      - virtualenv
      - python3-pip
    state: latest

- name: Create directory for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  copy:
    content: |
      deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    
- name: Install Docker CE
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin 

- name: Creates directory
  file:
    path: /home/vagrant/app
    state: directory

- name: Copiar el Dockerfile al servidor
  copy:
    src: ../Dockerfile
    dest: /home/vagrant/app/Dockerfile
    mode: '0644'

- name: Copiar docker compose al servidor
  copy:
    src: ../docker-compose.yml
    dest: /home/vagrant/app/docker-compose.yml
    mode: '0644'

- name: Asegurar que el grupo docker exista
  group:
    name: docker
    state: present

- name: Add the user 'vagrant' to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Copiar proyecto
  copy:
    src: src/
    dest: /home/vagrant/app/src/
    mode: '0644'

- name: Copiar tests
  copy: 
    src: test/
    dest: /home/vagrant/app/tests/
    mode: '0644'

- name: Copiar los requirements
  copy:
    src: ../requirements.txt
    dest: /home/vagrant/app/requirements.txt
    mode: '0644'

- name: Copiar los datos de migracion
  copy:
    src: migrations/
    dest: /home/vagrant/app/migrations/
    mode: '0644'

- name: Copiar el alembic file
  copy:
    src: ../alembic.ini
    dest: /home/vagrant/app/alembic.ini
    mode: '0644'

#- name: Construir imagen
#  docker_image:
#    name: flask_app_image
#    build:
#      path: /home/vagrant
#    state: present
#    source: build
#    
#- name: Levantar contenedor
#  docker_container:
#    name: flask_app
#    image: flask_app_image  
#    state: started
#    restart_policy: always
#    ports:
#      - "5000:5000"